### ISSUE TITLE
merged title

### ISSUE THREAD

**Issue by ElianNasatto** [MarkPflug/Sylvan.Data.Excel#155] opened 2024-02-22 15:36 UTC
I'm having trouble reading an xlsx file that contains the first line as a merged line title. Schema in the header does not work.

`System.FormatException: The input string 'was not in a correct format.`

Code:
```C#
var schema = Schema.Parse("Notes:string?");

// creates an Excel schema that can apply the above schema to an Excel worksheet.
var excelSchema = new ExcelSchema(hasHeaders: true,schema);

var options = new ExcelDataReaderOptions
{
    Schema = excelSchema// Isso indica que a primeira linha contém os títulos das colunas.
};

//using options or new reader options no header doesnt work

using ExcelDataReader edr = ExcelDataReader.Create(filepathwashere,
    new ExcelDataReaderOptions { Schema = ExcelSchema.NoHeaders });
{

    do
    {
        var sheetName = edr.WorksheetName;
        // enumerate rows in current sheet.
        while (edr.Read())
        {
            // iterate cells in row.
            // can use edr.RowFieldCount when sheet contains jagged, non-rectangular data
            for (int i = 0; i < edr.FieldCount; i++)
            {
                var value = edr.GetString(i);
            }
            // Can use other strongly-typed accessors
            // bool flag = edr.GetBoolean(0);
            // DateTime date = edr.GetDateTime(1);
            // decimal amt = edr.GetDecimal(2);
        }
        // iterates sheets
    } while (edr.NextResult());
}
```

![image](https://github.com/MarkPflug/Sylvan.Data.Excel/assets/51443571/6c5e561d-c22b-4e27-ac08-066c89fe9046)

**Comment by MarkPflug** [comment] 2024-02-22 16:11
I can't reproduce this with the information you've given. The following coded works just fine with a similarly shaped (merged title row) excel file:

```C#
using Sylvan.Data;
using Sylvan.Data.Excel;

class Program
{
    static void Main()
    {
        var schema = Schema.Parse("Notes:string?");

        // creates an Excel schema that can apply the above schema to an Excel worksheet.
        var excelSchema = new ExcelSchema(hasHeaders: true, schema);

        //var options = new ExcelDataReaderOptions{ Schema = excelSchema};

        var options = new ExcelDataReaderOptions { Schema = ExcelSchema.NoHeaders };

        using ExcelDataReader edr = ExcelDataReader.Create("test.xlsx", options);

        do
        {
            var sheetName = edr.WorksheetName;
            var r = 0;
            while (edr.Read())
            {
                r++;
                for (int i = 0; i < edr.RowFieldCount; i++)
                {
                    var value = edr.GetString(i);
                    Console.WriteLine($"{r},{i}:{value}");
                }
            }
        } while (edr.NextResult());
    }
}

```

As I said in the readme.md:

> Be aware that I will be unlikely to investigate any issue unless an example file can be provided reproducing the issue.

I need a file that reproduces the issue. Feel free to reopen this issue if you can provide a complete reproduction of the error, including a sample file.

**Closed by MarkPflug** 2024-02-22 16:11 UTC

**Comment by ElianNasatto** [comment] 2024-02-22 17:58
I was doing some tests and realized that the problem is not in the merged line but in the file editing protection. When I open it in Excel and activate editing, everything works correctly. Now I need to figure out how to remove this protection via code. Thank you for answering!
