### ISSUE TITLE
Can't read xls file

### ISSUE THREAD

**Issue by olekpa** [MarkPflug/Sylvan.Data.Excel#139] opened 2023-10-29 09:11 UTC
Cannot read this file [link removed]
which is totally fine and created by LibreOffice 7.2.5.2.

IndexOutOfRangeExeption
at Sylvan.Data.Excel.Ole2Package.NextSector(UInt32 sector)
at Sylvan.Data.Excel.Ole2Package.<GetStreamSectors>d__36.MoveNext()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at Sylvan.Data.Excel.Ole2Package.Ole2Entry.Open()
at Sylvan.Data.Excel.Xls.XlsWorkbookReader..ctor(Stream stream, ExcelDataReaderOptions options)
at Sylvan.Data.Excel.ExcelDataReader.Create(Stream stream, ExcelWorkbookType fileType, ExcelDataReaderOptions options)
at Sylvan.Data.Excel.ExcelDataReader.Create(String filename, ExcelDataReaderOptions options)

**Comment by MarkPflug** [comment] 2023-10-29 15:20
Post the file to this issue. I can't download it from whatever that site is.

**Comment by olekpa** [comment] 2023-10-30 08:48
Sure. Here it is: 
[data2.xls](https://github.com/MarkPflug/Sylvan.Data.Excel/files/13202224/data2.xls)
Excel 2016 doesn't like cell H4, could this be the problem?
But again it's fine for LibreOffice.

**Comment by MarkPflug** [comment] 2023-11-03 23:16
Thanks. I'm able to reproduce the issue and understand what the problem is. It will take me some time to get a fix for it though.

**Comment by MarkPflug** [comment] 2024-04-25 22:38
This is fixed in 0.4.20, just pushed to nuget.

**Closed by MarkPflug** 2024-04-25 22:38 UTC
