### ISSUE TITLE
Unable to read some excel files - Error: Specified argument was out of the range of valid values.     Parameter name: i

### ISSUE THREAD

**Issue by GeorgeDondapatiTR** [MarkPflug/Sylvan.Data.Excel#88] opened 2022-09-01 11:16 UTC
Team,

We are unable to read some excel files and getting below error while reading data.
Message: 
    System.AggregateException : One or more errors occurred.
      ----> System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
    Parameter name: i

  Stack Trace: 
    AggregateException.Handle(Func`2 predicate)
    ExcelFileSylvanFileReader.ctor(Import import) line 39
    FileReaderFactory.GetFileReader(Import import) line 58
    Converter.ConvertFile(Import currentImport) line 68
    ConvertFile_ExcelReaderBaseTests.IndexOutOfRange() line 378
    --ArgumentOutOfRangeException
    XlsxWorkbookReader.GetSharedString(Int32 i)
    XlsxWorkbookReader.ParseRowValues()
    XlsxWorkbookReader.InitializeSheet()
    XlsxWorkbookReader.NextResult()
    XlsxWorkbookReader.ctor(Stream iStream, ExcelDataReaderOptions opts)
    ExcelDataReader.Create(Stream stream, ExcelWorkbookType fileType, ExcelDataReaderOptions options)
    ExcelSlyvanToBlockingCollection.Read() line 115
    <.ctor>b__0() line 29
    Task.InnerInvoke()
    Task.Execute()

[Data.xlsx](https://github.com/MarkPflug/Sylvan.Data.Excel/files/9469316/Data.xlsx)

**Comment by charles-durrant-tr** [comment] 2022-09-01 11:41
@MarkPflug data is attached above, if the file is resaved in Excel then the library can read the file. Note this file can be read by EPPlus and NPOI but the same error occurs in ClosedXml

**Comment by MarkPflug** [comment] 2022-09-01 15:56
This should be fixed with 0.3.1 which I just pushed to nuget. It might take a few minutes to show up in the search results.

This was caused by the shared string table not specifying the number of records, which apparently is not required by the spec, and Crystal Decisions decided not to provide it.

**Closed by MarkPflug** 2022-09-01 15:56 UTC

**Comment by charles-durrant-tr** [comment] 2022-09-02 09:15
You have to wonder why it's in the spec at all

**Comment by GeorgeDondapatiTR** [comment] 2022-09-02 09:56
Thanks for the quick update @MarkPflug. 
It has fixed the original issue [Specified argument was out of the range of valid values. Parameter name: i]. 
But we are getting another issue i.e. Date values are not reading properly, it returning number.
Creating another issue with detailed description.
