### ISSUE TITLE
Excel xlsx reader returns blank values for rows

### ISSUE THREAD

**Issue by charles-durrant-tr** [MarkPflug/Sylvan.Data.Excel#63] opened 2022-06-16 10:22 UTC
Hi Mark, 

I have an xlsx file whereby the read returns no values. I've debugged the issue and it's deep in the xml reading. I need to transfer the file privately, do you have a contact email, perhaps you could message me privately? charliedurrant at gmail dot com

Charlie

**Comment by MarkPflug** [comment] 2022-06-16 16:05
Took a look at the file and I see roughly where the issue is. It looks like the Apache POI tool creates a slightly strange format where it inlines string values in a way that I don't properly handle. It is definitely fixable, but it will take me a bit of time to figure out a solution that doesn't break other scenarios.

In the meantime, you can open the file in Excel and "Save as" a copy, the copy should then be able to be processed correctly.

**Comment by MarkPflug** [comment] 2022-06-16 20:31
Just pushed 0.1.12 to nuget with a fix for this.

**Closed by MarkPflug** 2022-06-16 20:31 UTC

**Comment by MarkPflug** [comment] 2022-06-18 19:52
@charles-durrant-tr I did notice one issue in the files you sent. There was an odd formatting style being applied in one of them that wasn't handled correctly, it ended up throwing an exception in the formatting code. I fixed that so that it will fallback to a standard format in those scenarios. This is pushed with 0.2.0-b0001 (prerelease). Give a try and see if it fixed the issues you saw. Anything still failing please create a new issue with specific details and I can take a look.
