### ISSUE TITLE
How do I get the values of the merged cells

### ISSUE THREAD

**Issue by lileyzhao** [MarkPflug/Sylvan.Data.Excel#71] opened 2022-07-05 06:21 UTC
The merged cell can only get the first value, the value of the following cell is empty, there is no solution to this.

Whether to get the cell in Reader that marks the current cell as merged and contains matrix data.

**Comment by lileyzhao** [comment] 2022-07-05 06:32
The above content is said to be in .xls file.

in .xlsx Cannot even get the value of the first cell of the merged cell.

![image](https://user-images.githubusercontent.com/8878704/177264097-d4e66425-40d1-4e91-ad93-382a1bc3351b.png)

**Comment by MarkPflug** [comment] 2022-07-05 15:21
My library makes no effort to handle merged cells in the way you expect. It will return the cell value only when accessing the top left cell in the merged range, which is how Excel stores the value internally. I just added unit tests showing this behavior is consistent for the three supported file types: https://github.com/MarkPflug/Sylvan.Data.Excel/commit/1c2151a6e09ec852809e2df52d6fc905b564ad51

The second issue (.xlsx) might be unrelated to merged cells, but I cannot know without an example file. If you can send a pull request with a failing unit test including the offending file I can take a look. Otherwise, I really can't begin to guess what the issue is.

**Comment by lileyzhao** [comment] 2022-07-06 04:06
about question 2：

I Think: If NoHeaders is not set,and not .Read(),I think in do-while, I should be able to read the cell value of the header.
             Perhaps my thoughts are wrong and you can ignore it.(i will close the issue)

![image](https://user-images.githubusercontent.com/8878704/177465872-1e86d6d5-35f2-4657-9b70-7cf7609caad0.png)

**Comment by lileyzhao** [comment] 2022-07-06 04:15
about question 1：

I understand your mind，And think it's right, don't do too much with it.

My question is, But I don't know how I know if the current cell is the merged cell, and the matrix data (A1:B3) of the current merged cell. If I know this data, I can handle the read behavior of the merged cell by myself.

Such as:

if( edr.IsMerge()){

var matrix=edr.GetMatrix()
// matrix maybe like {BeginCell:"A1",EndCell:"B3"}

// do myself
}


I'm not asking you to implement it, but only I'm having problems using your library.

**Comment by lileyzhao** [comment] 2022-07-06 04:37
about question 1：

If that doesn't fit your design idea, that's fine, it's already great.

**Comment by MarkPflug** [comment] 2022-07-06 14:57
The problem with merged cells is that that information is not in-line with the data. Instead (at least with xlsx), it is defined at the very end of the sheet xml. This means that the entire sheet data would need to be parsed before returning the first row of data. One of the design goals of my library was to provide very high performance, forward only access. Unfortunately, this is at odds with how merged cells work. I've never, personally, had to deal with a file that had merged cells, so it wasn't a feature I was interested in supporting fully.

As far as the other issue, the first row will be interpreted as headers by default. This means that calls to `GetName(ordinal)` will return the string value of the cell. If the first row is not headers, then you can set `new ExcelDataReaderOptions { Schema = ExcelSchema.NoHeaders }`, and the first row will only be available after calling `Read` for the first time.

Hopefully that explains the issues you were seeing.

**Comment by lileyzhao** [comment] 2022-07-07 04:06
I understand the explanation about merging cells. Thank you very much for your patience.

I have also learned about the NoHeaders configuration item, which has solved my problem. Thank you very much.

**Closed** 2022-07-07 04:07 UTC
